  - alias: "Temperature Weekdays Morning"
    trigger:
      platform: time
      at: "05:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      - service: climate.set_temperature
        data_template:
          temperature: '{{ states.input_number.slider_hi_temp.state }}'

  - alias: "Temperature Weekend Morning"
    trigger:
      platform: time
      at: "07:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: time
        weekday:
        - sat
        - sun
    action:
      - service: climate.set_temperature
        data_template:
          temperature: '{{ states.input_number.slider_hi_temp.state }}'

  - alias: "Temperature Weekdays ToWork"
    trigger:
      platform: time
      at: "08:00:00"
    condition:
      condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    action:
      - service: climate.set_temperature
        data_template:
          temperature: '{{ states.input_number.slider_lo_temp.state }}'

  - alias: "Temperature Weekdays Afternoon"
    trigger:
      platform: time
      at: "14:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      - service: climate.set_temperature
        data_template:
          temperature: '{{ states.input_number.slider_hi_temp.state }}'

  - alias: "Temperature Night"
    trigger:
      platform: time
      at: "21:00:00"
    action:
      - service: climate.set_temperature
        data_template:
          temperature: '{{ states.input_number.slider_lo_temp.state }}'

#  - alias: "Sunset"
#    trigger:
#      platform: sun
#      event: sunset
#      offset: '-00:45:00'
#   action:

#  - alias: "Sunrise"
#    trigger:
#      platform: sun
#      event: sunrise
#      offset: '00:45:00'
#    action:
