  - alias: "Temperature Weekdays Morning"
    trigger:
      platform: time
      at: "05:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      - service: climate.set_temperature
        data:
          #entity_id: climate.kitchen
          temperature: input_slider.slider_hi_temp

  - alias: "Temperature Weekend Morning"
    trigger:
      platform: time
      at: "07:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: time
        weekday:
        - sat
        - sun
    action:
      - service: climate.set_temperature
        data:
          #entity_id: climate.kitchen
          temperature: input_slider.slider_hi_temp

  - alias: "Temperature Weekdays ToWork"
    trigger:
      platform: time
      at: "08:00:00"
    condition:
      condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    action:
      - service: climate.set_temperature
        data:
          #entity_id: climate.kitchen
          temperature: input_slider.slider_lo_temp

  - alias: "Temperature Weekdays Afternoon"
    trigger:
      platform: time
      at: "14:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      - service: climate.set_temperature
        data:
          #entity_id: climate.kitchen
          temperature: input_slider.slider_hi_temp

  - alias: "Temperature Night"
    trigger:
      platform: time
      at: "21:00:00"
    action:
      - service: climate.set_temperature
        data:
          #entity_id: climate.kitchen
          temperature: input_slider.slider_lo_temp
