Vacation:
  entities:
    - input_boolean.vacation_mode

Automation:
  entities:
    - automation.nas_readynas_notification
    - automation.nas_ds218_notification
    - automation.nodemcu_notification
    - automation.speedtest_network_notification
    - automation.speedtest_network_notification_ok
    - automation.nest_protect_emergency
    - automation.nest_protect_offline
    - automation.update_notifications
    - automation.sunrise
    - automation.sunset
    - automation.temperature_night
    - automation.temperature_weekdays_high
    - automation.temperature_weekdays_low
    - automation.temperature_weekend_high

Automation_view:
  view: yes
  icon: mdi:home-automation
  name: Automation
  entities:
    - group.automation
    - group.vacation
